### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [KamWithK/AnkiconnectAndroid#12]
May I ask what license you put your app under? You probably only forgot to declare it. If unsure, maybe pick a FOSS one that's approved by OSI/FSF? You can find [a list here](https://spdx.org/licenses/). Thanks!

**Comment by KamWithK** [comment]
I will include an MIT License file within the repo soon (didn't realise there wasn't one and didn't think anyone would really care haha)
Thanks for mentioning 😄

**Comment by IzzySoft** [comment]
Thanks! Looking forward to that (just wondering the issue is already closed but the license not yet there :see_no_evil:).

While on it: The APK attached to release 1.5-beta identifies as

    package: name='com.kamwithk.ankiconnectandroid' versionCode='6' versionName='1.4'

thus not matching the tag name. Was that intended, or was the wrong APK attached accidentally?

**Comment by KamWithK** [comment]
License file I'll include later on
There is no hurry, I doubt it'll make any difference as to how people use it (nor would I want it to, hence MIT)
Feel free to use this project however you want!
I'll double check the version details before the next release which shouldn't be too far off

**Comment by IzzySoft** [comment]
> I doubt it'll make any difference as to how people use it

Might only partly apply. For example, [F-Droid](https://f-droid.org/) only accepts apps with a F/LOSS license clearly declared, and so does [my repo](https://apt.izzysoft.de/fdroid).

> Feel free to use this project however you want!

That sounds like the [WTFPL](https://spdx.org/licenses/WTFPL.html) then :see_no_evil:

> I'll double check the version details before the next release which shouldn't be too far off

Thanks! Please give me a ping (e.g. by a comment here) when it's up then.

**Comment by KamWithK** [comment]
I believe MIT is a FOSS license and is what I'm looking for

**Comment by KamWithK** [comment]
Repository now has the license file, hope that helps you out 😄

**Comment by IzzySoft** [comment]
Thanks a lot! Your app will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.kamwithk.ankiconnectandroid) now with the next sync around 7 pm UTC. You're welcome then to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme if you wish. And if you like, I can send you a PR with the metadata I've set up for that in [Fastlane format](https://gitlab.com/-/snippets/1895688), which is commonly used for that, so you could control how your app is presented (adjust description, add screenshots etc); all that would then be pulled along with each release you make (my updater checks once per day for new tags with APKs attached).
