### ISSUE TITLE
Addnote api doesn't add audio from url

### ISSUE THREAD

**Issue by sp3ctum** [KamWithK/AnkiconnectAndroid#17]
I have had some time to play with ankiconnect card adding with my hare dictionary project. I have the addNote api working for the desktop ankiconnect. With that I am able to add a note and download an audio file which is then added to the note. For this I am using the following:

```json
{
    "action": "addNote",
    "version": 6,
    "params": {
        "note": {
            "deckName": "reserve",
            "modelName": "Japanese 2022 new accent note",
            "fields": {
                "Expression": "これは、ユウキさんのお母さんですか。",
                "Meaning": "ゆう‐き【勇気】\n<mark>ゆう‐き</mark>【<mark>勇気</mark>】<br />いさましい意気。物に恐れない気概。<span class=\"quote border border-dark rounded mr-3\">\n              「―をふるう」\n              <span class=\"quote-actions\" data-quote=\"―をふるう\"></span>\n            </span><span class=\"quote border border-dark rounded mr-3\">\n              「―がわく」\n              <span class=\"quote-actions\" data-quote=\"―がわく\"></span>\n            </span><br />⇒ゆうき‐づ・ける【勇気付ける】<br />⇒ゆうき‐りんりん【勇気{{zb93e}}{{zb93e}}】<br />",
                "Audio": "",
                "Focus": "勇気",
                "Meaning2": "Is this Yuki's mother?",
                "Snapshot": ""
            },
            "tags": [
                "hare"
            ],
            "options": {
                "allowDuplicate": true
            },
            "audio": [
                {
                    "url": "https://receptomanijalogi.web.app/audio/bunpro/これは、ユウキさんのお母さんですか。.mp3",
                    "filename": "hare_勇気_2023-01-03T08:29:48.268Z",
                    "fields": [
                        "Audio"
                    ]
                }
            ]
        }
    }
}
```

With AnkiconnectAndroid it seems the `params.note.audio` thing is ignored. If this is this by design, I'm fine with it. I think I can switch to using the storeMediaFile api and get the same result with two api calls.

**Comment by KamWithK** [comment]
Hello,
Ankiconnect Android is unofficial and just made/maintained by me so I just took the Ankiconnect features Yomichan actively used (from my observation) and added support for those

If you want to use different features you can put a PR in 😄  (or as you mentioned you can just do it the alternative way which is already supported)

**Comment by KamWithK** [comment]
Been a while without any activity so closing this issue
Feel free to reopen later though 😃
