### ISSUE TITLE
Audio for other languages

### ISSUE THREAD

**Issue by HaiDuongdarkocean** [KamWithK/AnkiconnectAndroid#34]
How can I change Forvo JP to Chinese? Please help me :"<

**Comment by KamWithK** [comment]
Occasionally I've built a custom version for Chinese users, but it's probably worth adding an option to the UI page for changing the language

**Comment by aharper14** [comment]
Any updates on this?

**Comment by KamWithK** [comment]
This should be a very easy feature to add (hence I'm keeping it open), however I haven't had anyone volunteer to implement it so far
I may at some point just do it myself but given that I've only had ~3 people requesting Chinese audio ever I don't think it's a priority for me to work on right now

That being said, if you want to see this feature added (for Chinese or other languages) then reply here so I can track its popularity

**Comment by cyra23** [comment]
I'm interested in Chinese audio too

**Comment by Twinov** [comment]
Made a PR to add a setting to switch Forvo language, @KamWithK would you be able to take a look? #51

**Comment by KamWithK** [comment]
> Made a PR to add a setting to switch Forvo language, @KamWithK would you be able to take a look? #51

Hey man sorry for the late reply
Been really busy starting a new job but I should be able to review and merge it soon!

**Comment by Twinov** [comment]
Congrats on the job and np!

**Comment by KamWithK** [comment]
Ankiconnect Android now supports a variety of languages including Chinese @HaiDuongdarkocean @aileks @cyra23 @PtPhoenix

**Comment by KamWithK** [comment]
Closing as this feature has been added

**Comment by KamWithK** [comment]
> Thank you so much! Will it be in release version? Or how can we update the app to have this feature?

I'll build and create a new release within a week

**Comment by KamWithK** [comment]
> Thank you so much! Will it be in release version? Or how can we update the app to have this feature?

Hey man sorry it took me a while to get around to but I've uploaded a new release which includes multiple language support
