### ISSUE TITLE
Adding card error

### ISSUE THREAD

**Issue by koutei7** [KamWithK/AnkiconnectAndroid#35]
I've been trying to use ankiconnect android with Kiwi and yomichan and I keep getting this error. I've double checked my yomichan settings and everything seems fine so I'm not sure if I'm missing anything. Any help would be greatly appreciated. 
![Screenshot_20230430_201726_Kiwi Browser](https://user-images.githubusercontent.com/131212907/235367637-407a4a17-0c84-44ce-ab3b-1a32899c76a9.jpg)

**Comment by KamWithK** [comment]
Hey @koutei7, have you read through the README instructions on common issues and how to go about solving them?
I'd suggest starting with those
If starting from scratch doesn't resolve your issues, feel free to reopen this issue or message on The Moe Way
