### ISSUE TITLE
Merge media logic of addNote + updateNoteFields

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [KamWithK/AnkiconnectAndroid#41]
For some reason, when reviewing #31 and #28, I didn't realize that the same media-handling logic was pretty much implemented in two separate ways. A [future version of ZXY101's mokuro fork](https://discord.com/channels/617136488840429598/1073399079264067606/1118288285027020930) requires `updateNoteFields` and `url` to work, and merging the logic of the two would be a simple way to support this.

@sp3ctum @Twinov As of writing this issue, I'm currently working on doing exactly this. Would y'all be interested in reviewing the PR whenever it comes?

**Comment by Twinov** [comment]
Sure. And yeah I think I remember looking at #28 and thinking that it would be good to extend the url logic to #31, I just didn't need it so I didn't bother :p

**Comment by Aquafina-water-bottle** [comment]
Quick update: it seems like the fork is no longer using `url` and is using `data`, and this is already supported by `updateNoteFields`, so this issue is no longer very high priority for me. WIP / untested code can be found here for the time being: #43 

If y'all are interested in continuing it, feel free to make another PR based off of it. Otherwise, I'll ping y'all sometime in the future when I'm actually done testing it a bit.

**Comment by KamWithK** [comment]
I'm going to close this issue then @Aquafina-water-bottle
If anyone else wants to work on this just comment and I will reopen it up
