### ISSUE TITLE
Crashing on Android 6.0

### ISSUE THREAD

**Issue by mathewthe2** [KamWithK/AnkiconnectAndroid#5]
Device: Boox Nova Pro 7.8
Android: 6.0.1

Message: "Unfortunately, Ankiconnect Android has stopped."

This is unfortunate because everything else, including Kiwi Browser, Yomichan, and AnkiDroid work with this device.

**Comment by mathewthe2** [comment]
It seems the only issue is the notification channel that requires Android 8+.

After removing these three lines and building the app, it works on my e-reader running on Android 6.0. 

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/13146030/183797474-1a436fce-9b86-4c18-87f1-adcb4b9c0780.png">

Not sure what the notification channel is for but it doesn't affect the core functionality.

I'll attach my debug apk I built here in case anyone finds this, but an official build for old Android versions will be appreciated.

[ankiconnect_android_1_5_compatibility.apk.zip](https://github.com/KamWithK/AnkiconnectAndroid/files/9296028/ankiconnect_android_1_5_compatibility.apk.zip)

**Comment by KamWithK** [comment]
Hey @mathewthe2 thanks for creating this issue and sorry for my slow reply, I've been busy on exSTATic which is nearing release and getting back into immersion. If your Android version is old enough then you may be able to remove the notification channel with no consequences but on newer versions of Android that is necessary to allow the app to run in the background (from what I've read/memory, not a Android developer just someone trying to make something useful). If I get some time later on I'll look into this a little more and determine the best way to add backwards compatibility here (probably just checking version number before running those three lines is enough, assuming you didn't have to make any other changes?).
Good luck mining on Android!
