### ISSUE TITLE
Feature request: add option to specify language for forvo audio as a url parameter.

### ISSUE THREAD

**Issue by noah-evans** [KamWithK/AnkiconnectAndroid#56]
The yomichan forvo server anki addon allows you to specify the language in the url: https://github.com/jamesnicolas/yomichan-forvo-server?tab=readme-ov-file#configuration

This is very useful for me because I use multiple yomichan profiles for different languages, and by specifying the language in the url i don't have to keep changing the settings on the forvo server.

It would be great if the ankiconnect forvo server could get this feature too.

**Comment by KamWithK** [comment]
Open to PRs if someone wants to implement this
