### ISSUE TITLE
Add anki card greyed out

### ISSUE THREAD

**Issue by sangotan** [KamWithK/AnkiconnectAndroid#57]
Hey,

I just installed ankiconnect android and followed all the instructions, but the add card button always seems to be greyed out... I tried to fix it by enabling content scanning but doesn't work 

Any solutions please? 

Thanks
![Screenshot_2024-03-22-20-28-09-74_4d38fce200f96aeac5e860e739312e76](https://github.com/KamWithK/AnkiconnectAndroid/assets/163655028/a4839118-1f2b-4e11-bfe6-c86957904c2a)

**Comment by KamWithK** [comment]
Probably because duplicate checks are enabled and you already mined the word? Before requesting help for basic support requests please ask on TMW's Discord
