### ISSUE TITLE
[Improvement] Allow user modification of the webCorsOriginList.

### ISSUE THREAD

**Issue by Tigy01** [KamWithK/AnkiconnectAndroid#58]
Allow access and modification of the webCorsOriginList like in the desktop extension due to services like asbplayer needing to be added to the list in order to work properly. This would allow the same sentence mining work flow to work across devices.

**Comment by Tigy01** [comment]
Apologies I have just realized this is already doable through the CORS Host. However, it does not seem possible to add more that one?

**Comment by KamWithK** [comment]
Correct, more than one isn't currently supported but you can just use * anyways iirc
Feel free to create a PR though
