### ISSUE TITLE
Version 1.13 don't export image from mokuro reader app to anki

### ISSUE THREAD

**Issue by YashaNoos** [KamWithK/AnkiconnectAndroid#59]
As the title say I am unable to export images to newly created notes using https://reader.mokuro.app/ Anki integration while AnkiconnectAndroid 1.13 is running. After reverting back to 1.12 everything is working fine again. So not that big of a deal but I thought I ought to give you a heads up.
Tested and reproduced on both my samsung S6 lite and Honor P20.

**Comment by KamWithK** [comment]
Thanks for the bug report

**Comment by KamWithK** [comment]
Should be fixed in 1.14
