### ISSUE TITLE
AnkiDroid: update Third Party Apps description

### ISSUE THREAD

**Issue by david-allison** [KamWithK/AnkiconnectAndroid#66]
I mentioned that I'd love to see AnkiConnect for Android, and I was sent a link to this project. THANK YOU!!!!

I've added a link to the project on AnkiDroid's [Third Party Apps page](https://github.com/ankidroid/Anki-Android/wiki/Third-Party-Apps#ankiconnect-android). 

Feel free to update the description as you see fit (or close this issue without comment).

Thank you again!
-- David

**Comment by KamWithK** [comment]
Thanks mate
