### ISSUE TITLE
Very limited with instructions

### ISSUE THREAD

**Issue by noxxid3** [KamWithK/AnkiconnectAndroid#7]
Using a galaxy s7 fe tablet, i do not see or know how to install it. The guide you give is very limited. Downloaded the zip. But how do i install you give little to information on this matter.
How do i install it? All it says install, how do install 3rd party apps? Please give more instructions to it. I go to files extract it, ankidroid can't open it either. Please give more a more guided instructions.

**Comment by Draighneys** [comment]
Hi @noxxid3,
The asset you need to install is the apk not the zip which is the code. It allows you to install the application. Once installed you just have to execute (click on) it and that's it. 
If it doesn't allow you to download it you need to deactivate security in your settings.

**Comment by KamWithK** [comment]
Thanks @Draighneys for the answer

I don't have more instructions because it's as simple as installing an APK which isn't a AnkiconnectAndroid specific problem 😅
 
Hope you managed to get it set up, otherwise please ask more on TMW's Discord server where me and others can help with simpler stuff.
